name: deploy-release

on:
  - push

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -U build
      - name: Compile localization message files
        run: |
          python setup.py compile_catalog -t mkdocs
          python setup.py compile_catalog -t readthedocs
      - name: Build
        run: |
          python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          password: ${{ secrets.TESTPYPI_PASSWORD }}
